version: "3.7"

services:
  postgres:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data/pgdata
    env_file: ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    depends_on:
      - "postgres"
    build:
      context: .
    ports:
      - 8080:8080